### PR TITLE
Pull Request for delete

### PR DESCRIPTION
**Pull request by StormyW618**
Working on making our delete call for our database functional.

### CODE REVIEW

**Comment by juliayee** [comment]
I think this looks good! Have you tested it an appropriate amount? @StormyW618

**Comment by mcruz42** [comment]
Looks good, Storm! Thanks for your work

**Comment by CanlinCao** [comment]
Nice work! We now have a fully functional backend!

**Comment by StormyW618** [comment]
> Looks good, Storm! Thanks for your work

Thanks for your feedback! :)

**Comment by StormyW618** [comment]
> Nice work! We now have a fully functional backend!

Yes, with this we do!

**Pull request merged**
